/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 *
 * @author Felipe
 */
public class JFDocumentosFrame extends javax.swing.JFrame {
    public JFDocumentosFrame(String razaoSocial) {
        super("Documentos de " + razaoSocial);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        setSize(700, 500);
        setLayout(new BorderLayout());

        JLabel titulo = new JLabel("Visualização de Documentos (PDFs)", SwingConstants.CENTER);
        titulo.setFont(new Font("Arial", Font.BOLD, 16));
        
        JTextArea areaVisualizacao = new JTextArea();
        areaVisualizacao.setEditable(false);
        
        String simulacao = "Carregando PDFs para: " + razaoSocial + "\n\n" +
                           "---------------------------------------------------\n" +
                           "SIMULAÇÃO DE ARQUIVOS ENCONTRADOS:\n" +
                           "1. Contrato Social (Contrato_001.pdf)\n" +
                           "2. Cópia do CNPJ (CNPJ_Alfa.pdf)\n" +
                           "3. Última Alteração Contratual (Alteracao_15.pdf)\n\n" +
                           " * Para visualização real, use bibliotecas como PDFBox.";
        
        areaVisualizacao.setText(simulacao);
        
        add(titulo, BorderLayout.NORTH);
        add(new JScrollPane(areaVisualizacao), BorderLayout.CENTER);
        
        setLocationRelativeTo(null); 
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFDocumentosFrame.class.getName());

    /**
     * Creates new form JFDocumentosFrame
     */
    public JFDocumentosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFDocumentosFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
