/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;
import view.JFAprovacao;
/**
 *
 * @author Felipe
 */
public class JFMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFMenu.class.getName());

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jMenuItemConsulta = new javax.swing.JMenuItem();
        jMenuItemDenuncia = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 720));

        desktopPane.setToolTipText("");
        desktopPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Gestão");

        jMenuItemEditar.setText("Editar ONG");
        jMenuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEditar);

        jMenuItemConsulta.setText("Consulta");
        jMenuItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsulta);

        jMenuItemDenuncia.setText("Denuncia");
        jMenuItemDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDenunciaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDenuncia);
        jMenu1.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaActionPerformed
        // TODO add your handling code here:
    // 1. Verifica se a janela já está aberta para evitar duplicação (BOA PRÁTICA)
    for (JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof JFAprovacao) {
            try {
                frame.setSelected(true); // Traz para frente se já estiver aberta
                return;
            } catch (java.beans.PropertyVetoException ex) {
                // Ignora ou trata erro
            }
        }
    }
    
    JFConsulta consultaFrame = new JFConsulta(); 
    
    desktopPane.add(consultaFrame);
    consultaFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaActionPerformed

    private void jMenuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarActionPerformed
// 1. Verifica se a janela JFEditarONG já está aberta
    for (javax.swing.JInternalFrame openFrame : desktopPane.getAllFrames()) {
        
        if (openFrame instanceof JFEditarONG) {
            try {
                // O CAST AGORA É VÁLIDO porque JFEditarONG é um JInternalFrame
                JFEditarONG editarFrame = (JFEditarONG) openFrame; 
                
                editarFrame.setSelected(true);
                return;
            } catch (java.beans.PropertyVetoException ex) {
                // Tratamento de erro
            }
        }
    }
    
    // 2. CRIA A NOVA INSTÂNCIA (agora é um JInternalFrame)
    JFEditarONG editarFrame = new JFEditarONG(); 
    
    // 3. Configura e exibe
    editarFrame.pack(); 
    desktopPane.add(editarFrame);
    editarFrame.setVisible(true);
    
    // Centraliza
    editarFrame.setLocation(
        (desktopPane.getWidth() - editarFrame.getWidth()) / 2, 
        (desktopPane.getHeight() - editarFrame.getHeight()) / 2
    );

    }//GEN-LAST:event_jMenuItemEditarActionPerformed

    private void jMenuItemDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDenunciaActionPerformed
        // TODO add your handling code here:
// 1. Verifica se a janela já está aberta para evitar duplicação (BOA PRÁTICA)
    for (JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof JFDenuncia) {
            try {
                frame.setSelected(true); // Traz para frente se já estiver aberta
                return;
            } catch (java.beans.PropertyVetoException ex) {
                // Ignora ou trata erro
            }
        }
    }
    JFDenuncia denunciaFrame = new JFDenuncia(); 
    
    desktopPane.add(denunciaFrame);
    denunciaFrame.setVisible(true);
    
    }//GEN-LAST:event_jMenuItemDenunciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemConsulta;
    private javax.swing.JMenuItem jMenuItemDenuncia;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
